In [33]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import config

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


In [38]:
df = pd.read_csv('nba_elo.csv')
df.shape

(72039, 27)

In [ ]:
engine = create_engine(config.engine_url, future=True)

In [ ]:
with engine.connect() as conn:
            insert_game_id = insert(bets).values(
                game_id=
                
#             on_duplicate_game = insert_game_id.on_duplicate_key_update(
#                 game_id=)

            db_setup_logger.debug(f'trying to insert game: {game_id}')

#             conn.execute(on_duplicate_company)
            db_setup_logger.debug(f'game_id inserted')
            conn.commit()
            db_setup_logger.debug(f'game_id committed successfully')

changes in league scoring system, from 2010

In [35]:
as_datetime = pd.to_datetime(df['date'])

date_bound = pd.Timestamp('2010-01-01 00:00:00')

df.loc[:, 'date_as_dt'] = as_datetime
df.drop('date', axis=1)

df = df[df['date_as_dt'] > date_bound]
df = df.drop('date', axis=1)

df = df.reset_index().drop('index', axis=1)

In [41]:
df.T

0           1           2           3           4      \
date            1946-11-01  1946-11-02  1946-11-02  1946-11-02  1946-11-02   
season                1947        1947        1947        1947        1947   
neutral                  0           0           0           0           0   
playoff                NaN         NaN         NaN         NaN         NaN   
team1                  TRH         CHS         PRO         DTF         STB   
team2                  NYK         NYK         BOS         WSC         PIT   
elo1_pre            1300.0      1300.0      1300.0      1300.0      1300.0   
elo2_pre            1300.0   1306.7233      1300.0      1300.0      1300.0   
elo_prob1         0.640065    0.631101    0.640065    0.640065    0.640065   
elo_prob2         0.359935    0.368899    0.359935    0.359935    0.359935   
elo1_post        1293.2767   1309.6521   1305.1542   1279.6189   1304.6908   
elo2_post        1306.7233   1297.0712   1294.8458   1320.3811   1295.3092   
carm-elo1_pre          NaN         NaN         NaN         NaN         NaN   
carm-elo2_pre          NaN         NaN         NaN         NaN         NaN   
carm-elo_prob1         NaN         NaN         NaN         NaN         NaN   
carm-elo_prob2         NaN         NaN         NaN         NaN         NaN   
carm-elo1_post         NaN         NaN         NaN         NaN         NaN   
carm-elo2_post         NaN         NaN         NaN         NaN         NaN   
raptor1_pre            NaN         NaN         NaN         NaN         NaN   
raptor2_pre            NaN         NaN         NaN         NaN         NaN   
raptor_prob1           NaN         NaN         NaN         NaN         NaN   
raptor_prob2           NaN         NaN         NaN         NaN         NaN   
score1                66.0        63.0        59.0        33.0        56.0   
score2                68.0        47.0        53.0        50.0        51.0   
quality                  0           0           0           0           0   
importance             NaN         NaN         NaN         NaN         NaN   
total_rating           NaN         NaN         NaN         NaN         NaN   

                     5           6           7           8           9      \
date            1946-11-03  1946-11-04  1946-11-05  1946-11-05  1946-11-07   
season                1947        1947        1947        1947        1947   
neutral                  0           0           0           0           0   
playoff                NaN         NaN         NaN         NaN         NaN   
team1                  CLR         PIT         BOS         DTF         PHW   
team2                  TRH         WSC         CHS         STB         PIT   
elo1_pre            1300.0   1295.3092   1294.8458   1279.6189      1300.0   
elo2_pre         1293.2767   1320.3811   1309.6521   1304.6908   1277.9456   
elo_prob1         0.648932    0.606189    0.620204    0.606189    0.668764   
elo_prob2         0.351068    0.393811    0.379796    0.393811    0.331236   
elo1_post        1307.1233   1277.9456   1288.4139   1271.4624    1304.667   
elo2_post        1286.1534   1337.7448    1316.084   1312.8473   1273.2786   
carm-elo1_pre          NaN         NaN         NaN         NaN         NaN   
carm-elo2_pre          NaN         NaN         NaN         NaN         NaN   
carm-elo_prob1         NaN         NaN         NaN         NaN         NaN   
carm-elo_prob2         NaN         NaN         NaN         NaN         NaN   
carm-elo1_post         NaN         NaN         NaN         NaN         NaN   
carm-elo2_post         NaN         NaN         NaN         NaN         NaN   
raptor1_pre            NaN         NaN         NaN         NaN         NaN   
raptor2_pre            NaN         NaN         NaN         NaN         NaN   
raptor_prob1           NaN         NaN         NaN         NaN         NaN   
raptor_prob2           NaN         NaN         NaN         NaN         NaN   
score1                71.0        56.0    

In [42]:
# unique_game_id = df['team1'] + df['team2'] + df['date']
# for table "games"

0        TRHNYK1946-11-01
1        CHSNYK1946-11-02
2        PROBOS1946-11-02
3        DTFWSC1946-11-02
4        STBPIT1946-11-02
               ...       
72034    GSWDAL2022-05-26
72035    BOSMIA2022-05-27
72036    DALGSW2022-05-28
72037    MIABOS2022-05-29
72038    GSWDAL2022-05-30
Length: 72039, dtype: object

In [4]:
df.shape

(16047, 27)

In [5]:
df['neutral'].unique()

array([0, 1], dtype=int64)

In [6]:
df['playoff'].unique()

array([nan, 't', 'q', 's', 'c', 'f', 'p'], dtype=object)

nan= regular game, preliminary, quarter, semi, championship

In [7]:
df.columns

Index(['season', 'neutral', 'playoff', 'team1', 'team2', 'elo1_pre',
       'elo2_pre', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post',
       'carm-elo1_pre', 'carm-elo2_pre', 'carm-elo_prob1', 'carm-elo_prob2',
       'carm-elo1_post', 'carm-elo2_post', 'raptor1_pre', 'raptor2_pre',
       'raptor_prob1', 'raptor_prob2', 'score1', 'score2', 'quality',
       'importance', 'total_rating', 'date_as_dt'],
      dtype='object')

In [8]:
np.sort(df['importance'].unique())

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  76.,  77.,
        78.,  79.,  82.,  84.,  85.,  86.,  87.,  89.,  91.,  92.,  94.,
        95.,  96.,  98.,  99., 100.,  nan])

In [9]:
feats_to_drop = ['season', 'neutral', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'carm-elo1_pre', 'carm-elo2_pre', 'carm-elo_prob1', 'carm-elo_prob2',
       'carm-elo1_post', 'carm-elo2_post', 'raptor1_pre', 'raptor2_pre',
       'raptor_prob1', 'raptor_prob2', 'quality',
       'importance', 'total_rating']

In [10]:
df = df.drop(feats_to_drop, axis=1)

feature engineering target variable

In [11]:
win_col_bool = (df.score1 < df.score2)
df['team_won'] = win_col_bool.astype('int') + 1
df = df.drop(['score1', 'score2'], axis=1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16047 entries, 0 to 16046
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   playoff     1095 non-null   object        
 1   team1       16047 non-null  object        
 2   team2       16047 non-null  object        
 3   elo1_pre    16047 non-null  float64       
 4   elo2_pre    16047 non-null  float64       
 5   date_as_dt  16047 non-null  datetime64[ns]
 6   team_won    16047 non-null  int32         
dtypes: datetime64[ns](1), float64(2), int32(1), object(3)
memory usage: 815.0+ KB


In [13]:
df['enc_playoff'] = df['playoff'].notna().astype(int)

In [14]:
df = df.drop('playoff', axis=1)

In [15]:
df

team1 team2     elo1_pre     elo2_pre date_as_dt  team_won  enc_playoff
0       BOS   TOR  1660.570200  1496.282300 2010-01-02         1            0
1       IND   MIN  1374.847800  1304.970300 2010-01-02         1            0
2       NJN   CLE  1302.088900  1742.092500 2010-01-02         2            0
3       UTA   DEN  1560.920000  1598.805400 2010-01-02         2            0
4       POR   GSW  1574.627400  1397.983900 2010-01-02         1            0
...     ...   ...          ...          ...        ...       ...          ...
16042   GSW   DAL  1638.484100  1663.411712 2022-05-26         1            1
16043   BOS   MIA  1733.061835  1673.667573 2022-05-27         1            1
16044   DAL   GSW  1663.411712  1638.484100 2022-05-28         1            1
16045   MIA   BOS  1673.667573  1733.061835 2022-05-29         1            1
16046   GSW   DAL  1638.484100  1663.411712 2022-05-30         1            1

[16047 rows x 7 columns]

In [16]:
# date_bound = df['date_as_dt'].quantile(.70)
# date_bound
date_bound = pd.Timestamp('2018-01-01 00:00:00')

In [17]:
train = df[df['date_as_dt'] < date_bound]
test = df[~(df['date_as_dt'] < date_bound)]

train.shape, test.shape

((10334, 7), (5713, 7))

In [18]:

X_train = train.drop('team_won', axis=1)
y_train = train['team_won']

X_test = test.drop('team_won', axis=1)
y_test = test['team_won']

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((10334, 6), (5713, 6), (10334,), (5713,))

In [19]:
cols = ['team1', 'team2']

le = LabelEncoder()
le.fit(X_train['team1'])

X_test['team1'] = X_test['team1'].map(lambda s: '<unknown>' if s not in le.classes_ else s)
X_test['team2'] = X_test['team2'].map(lambda s: '<unknown>' if s not in le.classes_ else s)

le.classes_ = np.append(le.classes_, '<unknown>')

X_train['enc_team1'] = le.transform(X_train['team1'])
X_train['enc_team2'] = le.transform(X_train['team2'])
X_test['enc_team1'] = le.transform(X_test['team1'])
X_test['enc_team2'] = le.transform(X_test['team2'])

X_train = X_train.drop(cols, axis=1)
X_test = X_test.drop(cols, axis=1)

In [20]:
X_train

elo1_pre     elo2_pre date_as_dt  enc_playoff  enc_team1  enc_team2
0      1660.570200  1496.282300 2010-01-02            0          1         28
1      1374.847800  1304.970300 2010-01-02            0         11         17
2      1302.088900  1742.092500 2010-01-02            0         18          5
3      1560.920000  1598.805400 2010-01-02            0         29          7
4      1574.627400  1397.983900 2010-01-02            0         25          9
...            ...          ...        ...          ...        ...        ...
10329  1382.991131  1405.826206 2017-12-31            0         26         14
10330  1630.909293  1377.066584 2017-12-31            0         10         13
10331  1517.552883  1459.818493 2017-12-31            0         12          4
10332  1567.824389  1467.842159 2017-12-31            0         21          6
10333  1380.746210  1450.291861 2017-12-31            0         24         23

[10334 rows x 6 columns]

turning datetime into integer

In [21]:
X_train['date_as_dt'] = X_train['date_as_dt'].apply(lambda x: x.value) / 10**9
X_test['date_as_dt'] = X_test['date_as_dt'].apply(lambda x: x.value) / 10**9

In [22]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train_ss = scaler.transform(X_train)
X_test_ss = scaler.transform(X_test)


X_train = pd.DataFrame(data=X_train_ss, columns=X_train.columns)
X_test = pd.DataFrame(data=X_test_ss, columns=X_test.columns)
X_train.shape, X_test.shape

((10334, 6), (5713, 6))

baseline model 1

In [23]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [24]:
y_pred = lr.predict(X_test)

print(classification_report(y_test, y_pred))
(y_pred == y_test).isna().sum()

              precision    recall  f1-score   support

           1       0.66      0.78      0.71      3224
           2       0.63      0.48      0.54      2489

    accuracy                           0.65      5713
   macro avg       0.64      0.63      0.63      5713
weighted avg       0.65      0.65      0.64      5713



0

baseline model using elos

In [25]:
elo_col_bool = (X_test['elo1_pre'] < X_test['elo2_pre']).astype(int)
results = elo_col_bool + 1
(results == y_test.reset_index()['team_won']).sum() / X_test.shape[0]

0.6381935935585507

In [26]:
print(classification_report(y_test, results))

              precision    recall  f1-score   support

           1       0.70      0.62      0.66      3224
           2       0.57      0.66      0.61      2489

    accuracy                           0.64      5713
   macro avg       0.64      0.64      0.64      5713
weighted avg       0.65      0.64      0.64      5713



baseline model 2

In [27]:
X_train = X_train.drop('date_as_dt', axis=1)
X_test = X_test.drop('date_as_dt', axis=1)

In [28]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [29]:
y_pred = lr.predict(X_test)

print(classification_report(y_test, y_pred))
(y_pred == y_test).isna().sum()

              precision    recall  f1-score   support

           1       0.65      0.81      0.72      3224
           2       0.64      0.44      0.52      2489

    accuracy                           0.65      5713
   macro avg       0.65      0.62      0.62      5713
weighted avg       0.65      0.65      0.63      5713



0

baseline model using only elo scores (baseline model 3)

In [30]:
elo_col_bool = (X_test['elo1_pre'] < X_test['elo2_pre']).astype(int)
results = elo_col_bool + 1
(results == y_test.reset_index()['team_won']).sum() / X_test.shape[0]

0.6381935935585507

In [31]:
print(classification_report(y_test, results))

              precision    recall  f1-score   support

           1       0.70      0.62      0.66      3224
           2       0.57      0.66      0.61      2489

    accuracy                           0.64      5713
   macro avg       0.64      0.64      0.64      5713
weighted avg       0.65      0.64      0.64      5713



In [32]:
lr.predict_proba(X_test)

array([[0.70826286, 0.29173714],
       [0.75297025, 0.24702975],
       [0.80197084, 0.19802916],
       ...,
       [0.66858355, 0.33141645],
       [0.55802478, 0.44197522],
       [0.60164824, 0.39835176]])